Add sebin aum info
AY2324S2-CS2103-F09-4/tp pull request #23
Opened 2024-02-29 02:34 UTC by sebin0817

Resolves #18 

Added documentation for:
- #14 
- #16

2024-02-29 12:09 UTC, joenus requested changes
I think you might have missed out on adding the commands on the `Command summary`. Other than that, LGTM!

2024-03-01 01:11 UTC, joenus approved these changes

2024-03-01 01:16 UTC, joenus requested changes
Whoops, I think you missed out on updating the developer guide.

2024-03-01 04:38 UTC, joenus approved these changes

2024-03-04 12:08 UTC, rickkoh commented
Checked AboutUs, UserGuide and Developer Guide. LGTM 👍

2024-03-04 12:10 UTC, rickkoh approved these changes

2024-03-04 12:11 UTC, merged